# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MyCode/EDA/Vivado/CPU_SOC/CPU_SOC.srcs/sources_1/ip/dat_mem/dat_mem.xci
# IP: The module: 'dat_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyCode/EDA/Vivado/CPU_SOC/CPU_SOC.gen/sources_1/ip/dat_mem/dat_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dat_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/MyCode/EDA/Vivado/CPU_SOC/CPU_SOC.srcs/sources_1/ip/dat_mem/dat_mem.xci
# IP: The module: 'dat_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyCode/EDA/Vivado/CPU_SOC/CPU_SOC.gen/sources_1/ip/dat_mem/dat_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dat_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
