name: Check PR can be merged
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  Run-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically Merge PR
        uses: plm9606/automerge_actions@1.2.2
        with:
          # The label name to automatically merge. Default is "automerge".
          label-name: "automerge"
          # The number of reviewers to automatically merge. Default is 1.
          reviewers-number: 1
          # The merge method ("merge", "squash", "rebase"). Default is "merge"
          merge-method: "squash"
          # Let the bot delete the merged branch. true or false.
          auto-delete: false
          # GitHub WebHook Secret Token
          github-token: ${{ secrets.GITHUB_TOKEN }}
